name: Server Actions
 
on:
  delete:
    branches:
     - "!main"
     - "!deploy-*"
    
env:
  EVENT_NAME: ${{ github.event_name }}
  EVENT_REF: ${{ github.event.ref }}
  
jobs:
  actions:
    if: github.event.ref_type == 'branch' && github.event.ref
    runs-on: ubuntu-latest
    steps:
    - name: Connect to server
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: 'cd /var/www/projects && ./server_actions.sh ${{ env.EVENT_NAME }} ${{ env.EVENT_REF }}'
